source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Discord API wrapper
gem 'discordrb'
gem 'dotenv'
gem 'require_all'
gem 'rest-client'

group :development do
  gem 'rubocop'
  gem 'rubocop-rspec'
end

group :development, :test do
  gem 'pry'
  gem 'factory_bot'
  gem 'rspec'
end